name: Run tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  checks: write

jobs:

  run-gradle-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Get Chrome version
        run: chrome --version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Execute Gradle build
        run: ./gradlew clean test

      - name: Generate test report
        uses: dorny/test-reporter@v3
        if: success() || failure()
        with:
          name: gradle-test-results
          path: build/test-results/test/TEST-*.xml
          reporter: java-junit
          fail-on-error: true

  run-maven-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: maven

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Get Chrome version
        run: chrome --version

      - name: Run tests with Maven
        run: ./mvnw clean test

      - name: Generate test report
        uses: dorny/test-reporter@v3
        if: success() || failure()
        with:
          name: maven-test-results
          path: target/surefire-reports/TEST-*.xml
          reporter: java-junit
          fail-on-error: true